### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by yujialele** [wondervictor/dpl.pytorch#2]
你好，我有几个问题咨询一下。
1、您使用的pytorch版本能否告知一下。
2、您代码中目标提取的方式是dense box，我没有找到selectivesereach
3、您数据集和原作者一样使用的voc2007trian, voc2012 test，还是直接使用voc2012.

**Comment by wondervictor** [comment]
1. Pytorch 0.4.1 
2. proposals of selective search can be found in [fast r-cnn by rgb](https://github.com/rbgirshick/fast-rcnn/blob/master/data/scripts/fetch_selective_search_data.sh)
3. train and test on VOC12
